### ISSUE TITLE
Question: How to writte your own decoders?

### ISSUE THREAD

**Issue by ulisses-alves** [nvie/decoders#332]
How could one write the following Elm decoder?

```elm
intFromStringDecoder : Decoder Int
intFromStringDecoder =
    Decode.string
        |> Decode.map
            (\str ->
               String.toInt str
                   |> Maybe.map Decode.succeed
                   |> Maybe.withDefault (Decode.fail "Not a number")
             )
```

**Comment by nvie** [comment]
I just documented this a bit better in the README, please let me know if this is helpful! https://github.com/nvie/decoders#building-custom-decoders

In this case, I would recommend the following:

```js
import { map, regex } from 'decoders';

const intFromStringDecoder = map(
  regex(/^-?[0-9]+$/, 'Must only contain digits'),
  s => parseInt(s, 10),
);
```

Although you could more directly translate your example to JS using

```js
const intFromStringDecoder = map(string, s => parseInt(s, 10));
```

…this would still allow `intFromStringDecoder('foo') === NaN` instead of a decoding error — thanks JavaScript!  The regex version may be the best error message / debugging experience.

If you don't want to use a regex, you could also do this:

```js
const intFromStringDecoder = map(
  string,
  s => {
    const n = parseInt(s, 10);
    if (isNaN(n)) throw new Error('Must be number');
    return n;
  },
);
```
