### ISSUE TITLE
How to decode discriminated union types with nested json?

### ISSUE THREAD

**Issue by svdHero** [nvie/decoders#514]
Hi again :sweat_smile:,

in my front-end TypeScript code I have the following discriminated union (DU) type:
```typescript
type FooA = {
    duKind: "FooA",
    myPropA: string
}

type FooB = {
    duKind: "FooB",
    myPropB: number
}

type Foo = FooA | FooB
```

My back-end REST API returns either
```json
{
    "foo" : {
        "fooA": {
            "myPropA": "Hello World"
        }
    }
}
```
or
```json
{
    "foo" : {
        "fooB": {
            "myPropB": 42
        }
    }
}
```
depending on the DU case.

How can I map this to my DU types using decoders?
```typescript
const fooADecoder: Decoder<FooA> = ???;
const fooBDecoder: Decoder<FooB> = ???;
const fooDecoder: Decoder<Foo> = either2<Foo>(fooADecoder, fooBDecoder);
```
I guess for the `duKind` I can use the `constant` decoder, but the main problem is that I have to reduce the "object nesting" from `{ "foo": { "fooA": { "myPropA": ...} } }` in JSON to `{ myPropA: ... }` in TypeScript.

This problem probably is not limited to DUs, but a general question of how to reduce/compress/squeeze JSON object nesting levels within a decoder.

Any help would be much appreciated, since this is a show stopper for me right now.

**Comment by nvie** [comment]
There are multiple ways.

If you need to both validate and transform shapes, you can use `map()`. Map will run a decoder on a given value, validate it, and invoke a callback function where you can manually transform it after validation. While very powerful, I recommend not going too crazy with it.

### Alternative 1

To answer your question directly, [here's a gist](https://gist.github.com/nvie/af3f1153ecc18abe9fc20c98b021c972) that shows you how this can be done.  Notice [how the "FooA" and "FooB" decoders don't directly return the "FooA" and "FooB" types](https://gist.github.com/nvie/af3f1153ecc18abe9fc20c98b021c972#file-answer-514-alt-1-ts-L25-L26), but just the shapes they take in the JSON.  Because of that, you'll need to [do some manual mapping work](https://gist.github.com/nvie/af3f1153ecc18abe9fc20c98b021c972#file-answer-514-alt-1-ts-L30-L44) to both attach the `duKind` field and select which one is used.

### Alternative 2

An alternative approach (also using `map()`'ing) could be [this](https://gist.github.com/nvie/feb93821dac5c3dbe63a2ca952241c86).  Here, the `fooA` and `fooB` decoders will each [decode their own "attrs"](https://gist.github.com/nvie/feb93821dac5c3dbe63a2ca952241c86#file-answer-514-alt-2-ts-L23-L41) in the JSON, and then use a `map()` to "attach" the `duKind` to that object.  Then in the `Foo` decoder, based on whether it has a field `fooA` or `fooB`, it will select which decoder to use, and [strip off the extra level of fooA/fooB properties](https://gist.github.com/nvie/feb93821dac5c3dbe63a2ca952241c86#file-answer-514-alt-2-ts-L46-L47).

Both approaches work.

### Alternative 3 (best, if possible)

If, however, you have any control over the JSON shape, a simpler shape for this would be to let it match your types more directly:

```json
{
    "foo": {
        "duKind": "FooA",
        "myPropA": "Hello World"
    }
}
```

or:

```json
{
    "foo" : {
        "duKind": "fooB",
        "myPropB": 42
    }
}
```

Because then the decoders would be [more straight-forward](https://gist.github.com/nvie/b58386a11aae27b8d3152dfcd50f4b9a), and won't need any custom mapping.

Hope this all helps!

**Comment by svdHero** [comment]
Thank you so much for your help. I will have a look into Alternative 1 and 2. Unfortunately, Alternative 3 is not possible, because I have no power over the back-end which is written in F# and translating the F# DUs automagically to the above JSON format.

What is your gut feeling about Alt 1 and Alt 2 in the long run? Which one will keep my sanity best, once my app data structures grow? Any recommendation between the two?

**Comment by nvie** [comment]
That's too bad. I think alternative 2 has better properties, because it more cleanly separates the "attaching the duKind value" from the "stripping off the extra nesting level" bits, and is overall cleaner. (For example it takes care of the "fooA" _xor_ "fooB" bits, for which alternative 1 needs that custom exception throwing.)

I have never seen this particular way of serializing things, but if this is a pretty standard way of serializing things in F#, could you point me to some documentation? Happy to take a look and see if this could be generalized in a better way, with a specific decoder for shapes like this.

**Comment by svdHero** [comment]
It is a Newtonsoft.json plugin by Zaid Ajaj, which you can find here:
https://github.com/Zaid-Ajaj/Fable.Remoting/blob/570132b507c470c6bb3b05884f7ce175dd6e81ea/Fable.Remoting.Json/FableConverter.fs
and which is often used in the [SAFE stack](https://safe-stack.github.io/).
 
Our back-end team copied the above file, added it to our back-end solution and uses the `FableJsonConverter` type like this:
```fsharp
type Json = private Json of string

[<RequireQualifiedAccess>]
module Json =
    let private getNewtonsoftSettings () : Newtonsoft.Json.JsonSerializerSettings =
        let settings = Newtonsoft.Json.JsonSerializerSettings(
                        Formatting = Newtonsoft.Json.Formatting.Indented,
                        Culture = System.Globalization.CultureInfo.InvariantCulture,
                        NullValueHandling = Newtonsoft.Json.NullValueHandling.Ignore,
                        // See https://github.com/Zaid-Ajaj/Fable.Remoting/pull/110
                        DateParseHandling = Newtonsoft.Json.DateParseHandling.None
                        )
        settings.ContractResolver <- new RequireAllPropertiesContractResolver()
        settings.Converters.Add(new FableJsonConverter())
        settings
        
    /// Serialize an object to Json using Newtonsoft.Json
    let private newtonsoftSerialize : Serialize<'t> =
        fun (object: 't) ->
            let settings = getNewtonsoftSettings ()
            Newtonsoft.Json.JsonConvert.SerializeObject(object, settings)
            |> Json
```
This will serialize `optional` types, `result` types and DUs automagically to a JSON format as shown earlier.

**Comment by svdHero** [comment]
An additional question would also be, what I should do if `either9` is not sufficient? In my particular use case, there are two REST endpoints called `commands` and `queries` which respond with DUs for commands and queries.
That means, that with the solutions above I will certainly have a problem, because I have more than just 9 queries in my app.

**Comment by nvie** [comment]
Thanks for sharing that info and those links. I will have to look at that in-depth some other time.

Regarding your eitherN ask: they stack up. If you look at how `either9` [is defined](https://github.com/nvie/decoders/blob/e802e52c42556d81d613c96de175c0f4d22e6ef2/src/either.js#L109), you'll see you can keep expanding this to build any `eitherN` you want. I just included 9 out of the box, and stopped there.

For example, if you need 13, you could build it like this:

```ts
const myTypeWithThirteenValues = either9(... /* 8 items here */, either5(... /* 5 more here */));
```

>  Would it be possible to make `either` accept an array instead of a fixed number of arguments? I guess the array's type will be the problem...

Yeah, the inferred type will be the problem if you need a DU.  If the number of items is dynamic, then you can use [`oneOf`](https://github.com/nvie/decoders/#oneOf). See also, this note in the docs, which touches on this:

![Screen Shot 2020-06-16 at 14 48 43@2x](https://user-images.githubusercontent.com/83844/84776557-bd331c80-afe0-11ea-8de3-53662ed07416.png)

**Comment by nvie** [comment]
Although, if you're willing to not use TypeScript's _inference_, you can still get there, but it requires some amount of duplication in exchange for the ability to not have to nest these eithers.

For example, in:

```
import { oneOf, Decoder, guard } from "decoders";

const thing = oneOf(["foo", "bar", "qux"]);
const verify = guard(thing);

console.log(verify("unsafe input here") === "baz");
```

The inferred type of `thing` will be `Decoder<string>`.  This program will compile, and throw a runtime error via the decoder.

However, if you narrow the type yourself:

```ts
import { oneOf, Decoder, guard } from "decoders";

type Thing = "foo" | "bar" | "qux";

const thing: Decoder<Thing> = oneOf(["foo", "bar", "qux"]);
//           ^^^^^^^^^^^^^^

const verify = guard(thing);

console.log(verify("unsafe input here") === "baz");
```

Then the last line will be a _type_ error (= invalid program), so this won't ever return a runtime error.

**Comment by svdHero** [comment]
Just to clarify: `oneOf` does not take `Decoder`s as an argument, but only actual (constant) values, is that right?
That's why I did not look into it.

**Comment by nvie** [comment]
You're absolutely right. I was assuming you were talking about string-enums here. In that case, please disregard my last comment :)

**Comment by svdHero** [comment]
Thanks again for the help. I'll go with the nested solution then. :smile:
