### ISSUE TITLE
Unwrap Error Message from Guard

### ISSUE THREAD

**Issue by arb** [nvie/decoders#929]
I don't want to use a guard because I don't want to deal with a bunch of `try catch` blocks but I do want to know when it has failed so I can log the issue and respond with an HTTP message. This [write-up](https://nvie.com/posts/introducing-decoders/#error-messages) got me down the path of calling the decoder directly, rather than always wrapping a decoder in a guard.

I'm trying to do `decoder(VAL).map(() => {}).mapError((e) => {})` and execute logic when I know `VAL` has been decoded and typed or do something with `e` in `mapError`. I've examined the code and the docs in [lemons.js](https://github.com/nvie/lemons.js/blob/main/src/Result.js) and it's not clear to me how to get the nice `err.message` that using a guard gives you. I see the inbound argument to `mapError` is an `Annotation`; how can I extract the message from an `Annotation`?

I've tried `e.message` and `e.errValue()` and neither of them worked. I am using version 1.25 of decoders.

**Comment by nvie** [comment]
**Note upfront:** This is more complicated than it had to be, which is why I simplified it a lot in 2.0. To learn how to adopt from the old to the new APIs, see this [migration guide](https://github.com/nvie/decoders/blob/main/MIGRATING-v2.md). I would recommend it, because it also gets rid of the complexity incurred by the `lemons` and `debrief` dependencies. 🎉 

---

**To answer your question:** Before 2.0, you can use use the `debrief` library to serialize it directly. This is what the guard internally uses too (it's already a dependency).

Here's the relevant code you could copy:

https://github.com/nvie/decoders/blob/a39662384ee5f93444bc50adc1e9dc561c7512e2/src/guard.js#L29-L35

Where `blob` is your input.

Note that there are two ways to turn an `Annotation` into a textual error message:

1. Using `import { serialize } from 'debrief`, then calling `serialize(annotation)`. This will echo back the original input, and "inline" the error message in a human-readable form. Example of a possible returned multi-line string:
   ```
   {
     "foo": "bar",
           ^^^^^ Must be integer
   }
   ```
2. Using `import { summarize } from 'debrief`, then calling `summarize(annotation)`. This will return a list-of-strings, each containing the "path" into the object, and the error reason, without echoing back. Less human-friendly, but won't echo back any sensitive data. Example of returned array of strings:
   ```
   ['Value at key "bar": Must be integer']
   ```

Hope that helps!

**Comment by arb** [comment]
Hey @nvie thanks for the prompt and thorough reply! Upgrading doesn't seem like it's in the cards at the moment regrettably. I ended up doing something like this

```ts
function tryDecoderGuard<D extends d.Decoder<any>>(
  decoder: D,
  value: unknown,
): [Error, null] | [null, d.DecoderType<D>] {
  let decodedValue = null;
  let error = null;
  try {
    decodedValue = d.guard(decoder)(value);
  } catch (e: any) {
    error = e;
  }
  return [error, decodedValue];
}
```

So that way, we return a tuple with a decoded and typed value OR a guard error. The caller then can refine on that tuple and execute additional logic. I'm using this code in an Express server and going down the `.map` route would have been difficult to prevent multiple `res.send` from happening on a given request.
